from enum import Enum

class JobType(Enum):
    PREPROCESS = "PREPROCESS"
    BACKGROUND_REMOVAL = "BACKGROUND_REMOVAL"

class JobStatus(Enum):
    QUEUED="QUEUED"
    PROCESSING="PROCESSING"
    DONE="DONE"
    FAILED="FAILED"
    REJECTED="REJECTED"
